# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7366fdad61372808713b5e0ed44cdd6e5304549027d9a9bd0aef4055fe7c1fcb718a283bddd1d4d85d7bd7aa3256ec6e15f256c26d6d77db2bc64b3e7442618e
  secret_key_devise: 141d918cf24332b664911937981c3d752af2aaf86deb6435ad85f63b20a305fffdb9b7891373c5fdd8f60695b80d5f35488e253cf719e83625d3c832ba0b7d7c

test:
  secret_key_base: a256ef96badcc9d0f8f4e8581fa757db1ef452ef305af66e4531158bf8236e1543b94ab3c1234d0c5ee31fb7eb8c2eceb3a589743ec7ba5775a40b24599c21ff
  secret_key_devise: eef066a478d2362afd9e82457ba9f3e00671eef4094de8d10fe2581d441a03c1b51e48f7c7b5631044c0db8946387121b39319119842585a8d29622ab8a44e97

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_devise: <%= ENV["SECRET_KEY_DEVISE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_devise: <%= ENV["SECRET_KEY_DEVISE"] %>
